[package]
name = "cef"
version = "0.1.0"
edition = "2021"

[features]
dox = ["cef-sys/dox"]

[package.metadata.docs.rs]
features = [ "dox" ]

[workspace]
members = [
 "sys",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cef-sys = { version = "0.1", path = "sys" }
widestring = "1.0"

