[package]
name = "libcef-sys"
version = "117.2.5"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "cef-rs sys crate"

[lib]
name = "cef_sys"

[features]
dox = []

[package.metadata.docs.rs]
features = [ "dox" ]

[dependencies]

[dev-dependencies]
winit = "0.28"
